project:
  type: book

book:
  title: "EpidemiaR Introductory Materials"
  author: 
    - Justin Millar
    - Amir Siraj
  date: "6/20/2024"
  chapters:
    - index.qmd
    - base-r-intro.qmd
    - if-statements.qmd
    - more-base.qmd
    - pipes.qmd
    - dpylr-tidyr-intro.qmd
    - joins.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt
  docx:
    toc: false
    highlight-style: github


editor: visual

