project:
  type: book

book:
  title: "EpidemiaR Introductory Materials"
  author: 
    - Justin Millar
    - Amir Siraj
  date: "6/20/2024"
  chapters:
    - index.qmd
    - part: base-r-intro.qmd
      chapters: 
        - if-statements.qmd
        - more-base.qmd
        - pipes.qmd
    - part: dpylr-tidyr-intro.qmd
      chapters: 
        - joins.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt
  docx:
    highlight-style: github


editor: visual

